

<h2 align='center'> Robert 'Ben' Pope </h2>
<h4 align='center'> poper38@gmail.com </h4>
<h4 align='center'> &#40;224&#41; 321-0465 </h4>

### Experience
<div class = "col-md-2">
<br><br>
<b>2019-2020</b>  

</div>

<div class = "col-md-10">
><b>Senior Data Mining Analyst</b>   
>American Greetings  
>Primary responisbilities include process improvement,
>automation, and research. In this role, I created Shiny
>WebApps to replace and improved SAS/Excel based reports.
>This project capitalized on Shiny's high ability for
>customization and automation. This project saved 60 hours
>of analysts' time per week, greatly improving the
>Analytics Team's capacity for meaningful analyses.
>In addition to traditional sales reporting available in 
>the legacy reports, these Apps featured dynamic 
>visualization, such as geographic sales performance, 
>top product images, store layouts, and various charts 
>and graphs.

</div>

<div class = "col-md-2">
<br><br>
<b>2017-2019</b>  

</div>  
<br>

<div class = "col-md-10">
><b>Senior Statistical Analyst</b>  
>Papyrus Recycled Greetings  
>Primary responsibilities included client relations, 
>and sales analytics.
> * Automated legacy reports
> * Played a pivotal role in creating new 

</div>

<div class = "col-md-2">
<br><br><br>
<b>2013-2017</b>  

</div>  
<br>
<div class = "col-md-10">
><b>Operations Research Analyst</b>  
>American Greetings  
>Primary responsibilities included solving optimization 
>problems and mathematical modeling. Achievements include

</div>

### Education
<div class = "col-md-2">
<br><br>
<b>2008-2012</b>  

</div>

<div class = "col-md-10">
><b>Grinnell College</b>  
>Bachelor Degree  
>Math and Statistics  

</div>
<div class = "col-md-2">
<br><br>
<b>2012-2013</b>  

</div>

<div class = "col-md-10">  
><b>University of Edinburgh</b>  
>Master of Science  
>Operational Research with Computational Optimization  

</div>

### Skills

<div class = "col-md-2">
<br><br><br>
<b>Technical Skills</b>  

</div>

<div class = "col-md-10">  
>Stochastic and deterministic modeling  
>Linear and non-linear programming  
>Simulation  
>Machine Learning  
>Test v. Control methodology  
>Version control

</div>

<div class = "col-md-2">
<br><br><br><br><br>
<b>Languages</b>  

</div>

<div class = "col-md-10">  
>R (Shiny)  
>Server SQL  
>SAS  
>VBA  
>C++  
>Java  
>HTML  
>Javascript  
>Very little Chinese

</div>



### Relevant Projects

<div class = "col-md-2">
<br><br>
<b>R Shiny Apps</b>  

</div>

<div class = "col-md-10">  
>A project to replace and improve various internal facing  
>reports. By replacing manual reports with completely automated  
>Web Apps, this project has saved 60 hours of analysts' time per  
>week, freeing analysts to do more complex analyses.

</div>

<div class = "col-md-2">
<br><br>
<b>Floor Planning</b>  

</div>

<div class = "col-md-10">  
>A project to dynamically determine optimal linear footage for  
>each product category in a given store. This required an  
>automated nonlinear programming solution

</div>

<div class = "col-md-2">
<br><br>
<b>Supply Chain Simulation</b>  

</div>

<div class = "col-md-10">  
>A stochastic model of the Corporate supply chain. This model is  
>used to estimate the impact of a change to shipping or  
>production without physical testing, and determine optimal  
>shipping policies.

</div>


### References

<div class = "col-md-2">
<br><br>
<b>Dave Visger</b>  

</div>

<div class = "col-md-10">  
>Relationship: Current manager  
>Phone: 216-213-4692  
>e-mail: dvisger@ag.com

</div>

<div class = "col-md-2">
<br><br>
<b>Lauren Dagiasis</b>  

</div>

<div class = "col-md-10">  
>Relationship: Previous manager  
>Phone: 216-224-9518  
>e-mail: Ldagiasis@gmail.com

</div>

<div class = "col-md-2">
<br><br>
<b>Kris Mills</b>  

</div>

<div class = "col-md-10">  
>Relationship: Co-worker  
>Phone: 330-727-5661  
>e-mail: kris.mills@amgreetings.com

</div>
